# language: node_js
# node_js:
#   - "14"
# dist: trusty

sudo: required
services:
  - docker

before_install:
  - docker build -t dmitriynoskov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dmitriynoskov/react-test npm test -- --coverage

after_success:
  - docker build -t dmitriynoskov/multi-client ./client
  - docker build -t dmitriynoskov/multi-nginx ./nginx
  - docker build -t dmitriynoskov/multi-server ./Server
  - docker build -t dmitriynoskov/multi-worker ./Worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push dmitriynoskov/multi-client
  - docker push dmitriynoskov/multi-nginx
  - docker push dmitriynoskov/multi-server
  - docker push dmitriynoskov/multi-worker
