language: node_js
node_js:
  - "14"
dist: trusty

sudo: required
services:
  - docker

before_install:
  - docker build -t dmitriynoskov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dmitriynoskov/react-test npm test -- --watchAll=false

after_success:
  - docker build -t dmitriynoskov/multi-client ./client
  - docker build -t dmitriynoskov/multi-nginx ./nginx
  - docker build -t dmitriynoskov/multi-server ./Server
  - docker build -t dmitriynoskov/multi-worker ./Worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push dmitriynoskov/multi-client
  - docker push dmitriynoskov/multi-nginx
  - docker push dmitriynoskov/multi-server
  - docker push dmitriynoskov/multi-worker

  

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-east-2-393264529200"
#   bucket_path: "multi-docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY